env:
  commonjs: true
  es6: true
  node: true
extends: [
  airbnb-base, 
  prettier
]
plugins: [
  prettier
]
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  linebreak-style: [error, windows],
  no-underscore-dangle: [error, {allow: [_id]}],
  prettier/prettier: [error]
}
